# Generated by Django 3.1.2 on 2020-10-13 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoollist', '0004_auto_20201013_1129'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('grade', 'section')},
        ),
    ]
