# Generated by Django 3.1.2 on 2020-10-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoollist', '0005_auto_20201013_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
