# Generated by Django 3.1.2 on 2020-10-14 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoollist', '0007_auto_20201014_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoollist.teachers', unique=True),
        ),
    ]
