# Generated by Django 3.1.2 on 2020-10-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoollist', '0009_auto_20201014_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
