# Generated by Django 3.1.2 on 2020-10-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoollist', '0010_teachers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='image',
            field=models.ImageField(default=11, upload_to='images/'),
            preserve_default=False,
        ),
    ]
