# Generated by Django 3.1.2 on 2020-10-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoollist', '0011_auto_20201014_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
