# Generated by Django 3.1.2 on 2020-10-14 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoollist', '0012_auto_20201014_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoollist.grade'),
        ),
    ]
