# Generated by Django 3.1.2 on 2020-10-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoollist', '0014_auto_20201014_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=100),
        ),
    ]
